from google import genai
from google.genai import types

from config import settings


async def generate_thumbnail(
    prompt: str,
    reference_images: list[bytes],
    personal_photos: list[bytes],
    logos: list[bytes] | None = None,
) -> bytes:
    client = genai.Client(api_key=settings.gemini_api_key)

    contents = []

    # Add reference thumbnails
    if reference_images:
        contents.append("Here are my reference thumbnails for style inspiration:")
        for img_bytes in reference_images:
            contents.append(
                types.Part.from_bytes(data=img_bytes, mime_type="image/png")
            )

    # Add channel logo(s)
    if logos:
        contents.append(
            "This is the channel logo. Place it in the EXACT same position "
            "and size as shown in the reference thumbnails. Use this actual "
            "image — do NOT recreate or write the logo text:"
        )
        for logo_bytes in logos:
            contents.append(
                types.Part.from_bytes(data=logo_bytes, mime_type="image/png")
            )

    # Add personal photos
    if personal_photos:
        contents.append(
            "Here are my personal photos. Pick the best one and place it in "
            "the thumbnail EXACTLY as it appears — do NOT modify, redraw, "
            "regenerate, or alter my face or body in any way. Use the ORIGINAL "
            "photo as-is, only adjusting size and position to fit the layout."
        )
        for img_bytes in personal_photos:
            contents.append(
                types.Part.from_bytes(data=img_bytes, mime_type="image/jpeg")
            )

    # Add the generation prompt
    contents.append(prompt)

    response = client.models.generate_content(
        model="gemini-3-pro-image-preview",
        contents=contents,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE", "TEXT"],
            image_config=types.ImageConfig(
                aspect_ratio="16:9",
            ),
        ),
    )

    for part in response.parts:
        if part.inline_data is not None:
            image = part.as_image()
            return image.image_bytes

    raise Exception("No image generated by Nano Banana")


async def generate_background(
    prompt: str,
    reference_images: list[bytes],
    logos: list[bytes] | None = None,
) -> bytes:
    """Generate ONLY background + logo, no person, no text."""
    client = genai.Client(api_key=settings.gemini_api_key)

    contents = []

    if reference_images:
        contents.append(
            "Here are reference thumbnails. Match the SAME visual style, "
            "color grading, and effects — but generate ONLY the background "
            "and logo. Do NOT include any person or any text."
        )
        for img_bytes in reference_images:
            contents.append(
                types.Part.from_bytes(data=img_bytes, mime_type="image/png")
            )

    if logos:
        contents.append(
            "This is the channel logo. Place it in the same position and size "
            "as in the reference thumbnails."
        )
        for logo_bytes in logos:
            contents.append(
                types.Part.from_bytes(data=logo_bytes, mime_type="image/png")
            )

    contents.append(prompt)

    response = client.models.generate_content(
        model="gemini-3-pro-image-preview",
        contents=contents,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE", "TEXT"],
            image_config=types.ImageConfig(
                aspect_ratio="16:9",
            ),
        ),
    )

    for part in response.parts:
        if part.inline_data is not None:
            image = part.as_image()
            return image.image_bytes

    raise Exception("No background image generated")
