from google import genai
from google.genai import types

from config import settings


async def generate_thumbnail(
    prompt: str,
    reference_images: list[bytes],
    personal_photos: list[bytes],
    logos: list[bytes] | None = None,
) -> bytes:
    client = genai.Client(api_key=settings.gemini_api_key)

    contents = []

    # Add reference thumbnails
    if reference_images:
        contents.append("Here are my reference thumbnails for style inspiration:")
        for img_bytes in reference_images:
            contents.append(
                types.Part.from_bytes(data=img_bytes, mime_type="image/png")
            )

    # Add channel logo(s)
    if logos:
        contents.append(
            "This is the channel logo. Place it in the EXACT same position "
            "and size as shown in the reference thumbnails. Use this actual "
            "image — do NOT recreate or write the logo text:"
        )
        for logo_bytes in logos:
            contents.append(
                types.Part.from_bytes(data=logo_bytes, mime_type="image/png")
            )

    # Add personal photos
    if personal_photos:
        contents.append(
            "Here are my personal photos. Pick the best one and place it in "
            "the thumbnail EXACTLY as it appears — do NOT modify, redraw, "
            "regenerate, or alter my face or body in any way. Use the ORIGINAL "
            "photo as-is, only adjusting size and position to fit the layout."
        )
        for img_bytes in personal_photos:
            contents.append(
                types.Part.from_bytes(data=img_bytes, mime_type="image/jpeg")
            )

    # Add the generation prompt
    contents.append(prompt)

    response = client.models.generate_content(
        model="gemini-3-pro-image-preview",
        contents=contents,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE", "TEXT"],
            image_config=types.ImageConfig(
                aspect_ratio="16:9",
                image_size="4K",
            ),
        ),
    )

    for part in response.parts:
        if part.inline_data is not None:
            image = part.as_image()
            return image.image_bytes

    raise Exception("No image generated by Nano Banana")


async def generate_background(
    prompt: str,
    reference_images: list[bytes],
    logos: list[bytes] | None = None,
    aspect_ratio: str = "16:9",
    image_size: str = "4K",
) -> bytes:
    """Generate ONLY background + logo, no person, no text."""
    client = genai.Client(api_key=settings.gemini_api_key)

    contents = []

    if reference_images:
        contents.append(
            "Here are reference thumbnails. Use them ONLY to understand the "
            "general layout, logo placement, and composition style (where elements go). "
            "Do NOT copy their colors, visual effects, or subject matter. "
            "The background you generate must be about the TOPIC described below — "
            "use visuals, colors, and imagery that represent THAT topic specifically. "
            "Generate ONLY the background and logo. Do NOT include any person or any text."
        )
        for img_bytes in reference_images:
            contents.append(
                types.Part.from_bytes(data=img_bytes, mime_type="image/png")
            )

    if logos:
        contents.append(
            "This is the channel logo. Place it in the same position and size "
            "as in the reference thumbnails."
        )
        for logo_bytes in logos:
            contents.append(
                types.Part.from_bytes(data=logo_bytes, mime_type="image/png")
            )

    contents.append(prompt)

    response = client.models.generate_content(
        model="gemini-3-pro-image-preview",
        contents=contents,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE", "TEXT"],
            image_config=types.ImageConfig(
                aspect_ratio=aspect_ratio,
                image_size=image_size,
            ),
        ),
    )

    for part in response.parts:
        if part.inline_data is not None:
            image = part.as_image()
            return image.image_bytes

    raise Exception("No background image generated")


async def composite_with_effects(
    background_bytes: bytes,
    person_bytes: bytes,
    reference_images: list[bytes],
    extra_instructions: str | None = None,
    aspect_ratio: str = "16:9",
    image_size: str = "4K",
) -> bytes:
    """Use Gemini to composite person onto background with effects matching references."""
    client = genai.Client(api_key=settings.gemini_api_key)

    contents = []

    # Show references so Gemini sees the person effects/glow/editing style
    if reference_images:
        contents.append(
            "Here are reference YouTube thumbnails. Study how the PERSON is composited "
            "into the background — the position, size, glow, lighting effects, color grading, "
            "edge blending, and any visual effects. You must replicate the SAME style."
        )
        for img_bytes in reference_images:
            contents.append(
                types.Part.from_bytes(data=img_bytes, mime_type="image/png")
            )

    # Provide the background
    contents.append(
        "This is the FINAL background image. It already contains the logo and all "
        "visual elements. You MUST use this EXACT image as the base layer — do NOT "
        "regenerate, redraw, or modify the background, logo, or any element in it. "
        "The ONLY change you make is placing the person on top:"
    )
    contents.append(types.Part.from_bytes(data=background_bytes, mime_type="image/png"))

    # Provide the person photo
    contents.append(
        "This is the person photo. Remove its original background and place "
        "the person onto the background image above:"
    )
    contents.append(types.Part.from_bytes(data=person_bytes, mime_type="image/png"))

    instructions = (
        "Instructions:\n"
        "1. PRESERVE the person's face and body EXACTLY — do NOT redraw, alter, or distort them\n"
        "2. Remove the person's original background completely\n"
        "3. Apply the SAME visual effects as the reference thumbnails — glow, lighting, "
        "color grading, edge effects, rim lighting, etc. to the person ONLY\n"
        "4. Position and size the person the SAME way as in the reference thumbnails\n"
        "5. Do NOT add any text\n"
        "6. CRITICAL: The background, logo, and all existing elements must remain "
        "PIXEL-PERFECT identical. Only the person is added on top."
    )
    if extra_instructions:
        instructions += f"\n7. Additional request from user: {extra_instructions}"
    contents.append(instructions)

    response = client.models.generate_content(
        model="gemini-3-pro-image-preview",
        contents=contents,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE", "TEXT"],
            image_config=types.ImageConfig(
                aspect_ratio=aspect_ratio,
                image_size=image_size,
            ),
        ),
    )

    for part in response.parts:
        if part.inline_data is not None:
            image = part.as_image()
            return image.image_bytes

    raise Exception("No composite image generated")


async def add_text_with_style(
    composite_bytes: bytes,
    text: str,
    reference_images: list[bytes],
    aspect_ratio: str = "16:9",
    image_size: str = "4K",
) -> bytes:
    """Use Gemini to add styled text to the composite, matching reference typography."""
    client = genai.Client(api_key=settings.gemini_api_key)

    contents = []

    if reference_images:
        contents.append(
            "Here are reference YouTube thumbnails. Study the TYPOGRAPHY carefully — "
            "the font style, font weight, text color, text size, text position, "
            "text effects (shadow, stroke, glow, gradient), and how the text is "
            "laid out relative to the person and background. You must replicate "
            "the SAME text style on the image below."
        )
        for img_bytes in reference_images:
            contents.append(
                types.Part.from_bytes(data=img_bytes, mime_type="image/png")
            )

    contents.append(
        "This is the current thumbnail (background + person already composited). "
        "Add text to it WITHOUT changing anything else — keep the background, "
        "person, logo, and all effects EXACTLY as they are:"
    )
    contents.append(types.Part.from_bytes(data=composite_bytes, mime_type="image/png"))

    contents.append(
        f'Add the following text to the thumbnail: "{text}"\n\n'
        f"Requirements:\n"
        f"1. Use the SAME font style, size, color, and effects as the reference thumbnails\n"
        f"2. Place the text in the same position/area as in the references\n"
        f"3. Make the text clearly readable and impactful\n"
        f"4. Do NOT change the background, person, logo, or any other element\n"
        f"5. The text should look like it belongs in this thumbnail series"
    )

    response = client.models.generate_content(
        model="gemini-3-pro-image-preview",
        contents=contents,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE", "TEXT"],
            image_config=types.ImageConfig(
                aspect_ratio=aspect_ratio,
                image_size=image_size,
            ),
        ),
    )

    for part in response.parts:
        if part.inline_data is not None:
            image = part.as_image()
            return image.image_bytes

    raise Exception("No text overlay image generated")
