from io import BytesIO

from google import genai
from google.genai import types

from config import settings


async def generate_thumbnail(
    prompt: str,
    reference_images: list[bytes],
    personal_photos: list[bytes],
    font_files: list[bytes],
) -> bytes:
    client = genai.Client(api_key=settings.gemini_api_key)

    contents = []

    # Add reference thumbnails
    if reference_images:
        contents.append("Here are my reference thumbnails for style inspiration:")
        for img_bytes in reference_images:
            contents.append(types.Part.from_bytes(data=img_bytes, mime_type="image/png"))

    # Add personal photos
    if personal_photos:
        contents.append("Here are my personal photos. Pick the best one for this thumbnail:")
        for img_bytes in personal_photos:
            contents.append(types.Part.from_bytes(data=img_bytes, mime_type="image/jpeg"))

    # Add font files
    if font_files:
        contents.append("Here are available fonts for the text:")
        for font_bytes in font_files:
            contents.append(types.Part.from_bytes(data=font_bytes, mime_type="font/ttf"))

    # Add the generation prompt
    contents.append(prompt)

    response = client.models.generate_content(
        model="gemini-2.5-flash-preview-image-generation",
        contents=contents,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE", "TEXT"],
        ),
    )

    for part in response.parts:
        if part.inline_data is not None:
            image = part.as_image()
            buffer = BytesIO()
            image.save(buffer, format="PNG")
            return buffer.getvalue()

    raise Exception("No image generated by Nano Banana")
